#!/usr/bin/env bash
# ralph_repo_inventory.sh — read-only repo file walker.
# Writes migration/inventory-report.md with one row per file:
#   path, size, mtime, sha256.
#
# Risk class: LOW (read-only). Always allowed.

set -euo pipefail

HERE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "$HERE/lib/common.sh"

ralph_parse_flags "$@"
if [[ ${RALPH_HELP:-0} -eq 1 ]]; then
  ralph_print_help_header "ralph_repo_inventory.sh" "Read-only repo file walker."
  cat <<EOF
WHAT IT DOES
  - Walks the repo (excluding .git, node_modules, __pycache__, build artifacts).
  - For each file: size, mtime ISO, sha256.
  - Writes migration/inventory-report.md.

RISK CLASS
  LOW (read-only). Safe to run any time.

OUTPUT
  prompts/ralph-meta-chain/migration/inventory-report.md
EOF
  exit 0
fi

ralph_require_repo

repo="$(ralph_repo_root)"
mig="$(ralph_migration_dir)"
out="$mig/inventory-report.md"

ralph_log "scanning $repo"

# Excluded dirs (do not inventory generated/external content).
exclude_dirs=(
  ".git"
  "node_modules"
  "__pycache__"
  ".venv"
  ".uv"
  "dist"
  ".pytest_cache"
  ".idea"
  ".vscode"
  ".npm"
)

find_args=()
for d in "${exclude_dirs[@]}"; do
  find_args+=( -name "$d" -prune -o )
done

# Build inventory body. We tee into a tmp first so the final write is atomic.
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  echo "---"
  echo "generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "generator: ralph_repo_inventory.sh"
  echo "repo_root: $repo"
  echo "---"
  echo
  echo "# Inventory Report"
  echo
  echo "Generated by \`migration/scripts/ralph_repo_inventory.sh\`."
  echo
  echo "## Files"
  echo
  echo "| Path | Bytes | mtime UTC | sha256 |"
  echo "|------|-------|-----------|--------|"

  count=0
  while IFS= read -r f; do
    [[ -f "$f" ]] || continue
    rel="${f#"$repo/"}"
    size="$(wc -c < "$f" | tr -d ' ')"
    mtime="$(date -u -r "$f" +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || stat -c %y "$f" 2>/dev/null | awk '{print $1"T"$2"Z"}')"
    sha="$(shasum -a 256 "$f" 2>/dev/null | awk '{print $1}')"
    [[ -z "$sha" ]] && sha="$(sha256sum "$f" 2>/dev/null | awk '{print $1}')"
    [[ -z "$sha" ]] && sha="—"
    echo "| $rel | $size | $mtime | $sha |"
    count=$((count + 1))
  done < <(find "$repo" "${find_args[@]}" -type f -print | sort)

  echo
  echo "## Summary"
  echo
  echo "- total files: $count"
  echo "- generated_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
} > "$tmp"

mkdir -p "$mig"
mv "$tmp" "$out"
trap - EXIT

ralph_log "wrote $out"
ralph_migration_log_append inventory "files=$(grep -cE '^\| ' "$out" | awk '{print $1-1}')" || true

echo "$out"
